### PR TITLE
Removed and Updated Following Sites

### PR DESCRIPTION
**Pull request by FMHYHelper**
Removed:
* [Onion](http://flibustahezeous3.onion/)
* [zqktlwi4fecvo6ri](http://zqktlwi4fecvo6ri.onion/wiki/Libraries)
* [audiobookbay.nl](http://audiobookbay.nl/) - Since it leads back to fi
* [Random Page](http://wikistroll.com/)
* [Litube](https://litube.net/)
* [mangaowls](https://mangaowls.com/) 
* [MangaOwl](https://mangaowl.net/) 
* [MoJoBB](https://mojobb.com/) - Books / Magazines
* [Clockwise Library](http://clockwise3rldkgu.onion/)
* [FindPDFDoc](http://www.findpdfdoc.com/) - It is supposed to be Document Search but directs to https://www.mireene.com/ which is some random site?
* [rvisualnovels-recs](https://sites.google.com/view/)  - It is supposed to be Visual Novels Recommendations but the site is just google sites? so I am not too sure. Anyway it throws a 404 error. 
* [xfmro77i3lixucja](http://xfmro77i3lixucja.onion/) 
* [KingAuthor](https://kingauthor.net/) - 403 Forbidden error 
* [16Chan Library](https://16chan.xyz/library/)
* [The Theosophical Society in Australia](http://www.austheos.org.au/clibrary/bindex-0.html)

Updated:
* **[Audiobook Bay](http://audiobookbay.ws/)** --> **[Audiobook Bay](http://audiobookbay.fi/)** 
* [AudiobookBay](http://audiobookbay.nl/forum/general-requests/) --> [AudiobookBay](http://audiobookbay.fi/forum/general-requests/)
* [PDFGet](http://www.pdfget.com/) --> [PDFGet](http://pdfget.com/)
* **[ForCoder](https://forcoder.su/)** --> **[ForCoder](http://forcoder.su/)**

### CODE REVIEW

**Comment by FMHYHelper** [comment]
Checked most if not all errors in fmhyedit/ReadingPiracyGuide.md (other than github repos)

**Review by nbats — COMMENTED** [review]
alright I applied all the changes, but did you check the .onion sites in tor?

**Comment by FMHYHelper** [comment]
> alright I applied all the changes, but did you check the .onion sites in tor?

yep I did

**Comment by nbats** [comment]
alright I'll remove those as well

**Pull request closed without merging**
