### PR TITLE
Removed Following site

### PR DESCRIPTION
**Pull request by FMHYHelper**
* [dato.rss](https://datorss.com/)

### CODE REVIEW

**Review by nbats — COMMENTED** [review]
looks like this is working now

**Comment by FMHYHelper** [comment]
> looks like this is working now

wait for me I am getting a 500 error.

**Comment by FMHYHelper** [comment]
image

**Comment by nbats** [comment]
yeah idk it was working for me earlier and now its not. We'll keep an eye on it I guess.

**Pull request closed without merging**
