### PR TITLE
New Microsoft Office guide

### PR DESCRIPTION
**Pull request by IverCoder**
I originally wrote those guides months ago. I decided to rewrite it again for better readability and clarity. Hope it helps.

### CODE REVIEW

**Comment by nbats** [comment]
thanks but looks like something went wrong and its giving +22,278 −22,278 additions / deletions. Would you mind just sending a link to it here instead?

**Comment by IverCoder** [comment]
> thanks but looks like something went wrong and its giving +22,278 −22,278 additions / deletions. Would you mind just sending a link to it here instead?

https://rentry.co/office-guide

I wanted to replace the pastebin and reddit link with this, as those links point to my older guide which was replaced by this newer one

**Comment by taskylizard** [comment]
This is now closed, but please don't edit the single-page file directly.

**Comment by nbats** [comment]
> 

thanks I'll get it added

**Pull request closed without merging**
