### PR TITLE
Update readingpiracyguide.md

### PR DESCRIPTION
**Pull request by stuffed18**
2 collections of thousands of light novels, including every series, on the internet archive. 200gb of books total.

### CODE REVIEW

**Comment by stuffed18** [comment]
btw could u send me a link to the fmhy discord? Thanks

**Comment by radiohead-sucks** [comment]
> btw could u send me a link to the fmhy discord? Thanks

the invites are open on fridays, just wait until then and be patient

**Comment by nbats** [comment]
thanks for sharing but neither allows you to view all of them on archive, and the epub DDL for both is dead

**Comment by InternetNinjo** [comment]
> wdym by that? I can view all of them and download them perfectly fine

Item not available
The item is not available due to issues with the item's content. 

you can download them it doesn't mean others can, please test it from another device or someone else.

**Comment by stuffed18** [comment]
Have you guys not used archive.org in the last month? That will happen for any page if you try download it like that. You have to click show all downloads to download the books, or use jdownloader to download all of them at once.

**Comment by nbats** [comment]
Alright I'm sorry I had no clue you had to do it that way, I'll get this added in the next update.

**Pull request closed without merging**
